import React, { useState, useEffect, useMemo } from 'react';
import { Search, Printer, ArrowUpDown, ChevronDown, ChevronUp } from 'lucide-react';
import toast, { Toaster } from 'react-hot-toast';
import { useSelector, useDispatch } from 'react-redux';
import { Analytics } from '@vercel/analytics/react';
import { toggleActivitySelection, setActivitySelection, clearActivitySelection, setLanguage } from './store/selectionSlice';

const translations = {
    en: {
        title: 'Activity Viewer',
        reportTitle: 'Selected Activities Report',
        activitySelectionReport: 'Activity selection report',
        searchPlaceholder: 'Search in all fields...',
        printButton: 'Print Selected',
        prevButton: 'Previous',
        nextButton: 'Next',
        loading: 'Loading...',
        noSelectionError: 'Please select at least one activity to print',
        autoGenerated: 'This report was auto-generated by Activity Viewer',
        activityId: 'Activity ID',
        descriptionAr: 'Description (Arabic)',
        descriptionEn: 'Description (English)',
        classification: 'Classification',
        saudisPercentage: 'Saudis %',
        date: 'Date',
        activityCount: 'Activity Count',
        jsonArrayTitle: 'Selected Activity IDs (JSON Array)',
        langToggle: 'العربية',
        footerTimestamp: 'at'
    },
    ar: {
        title: 'مستعرض الأنشطة',
        reportTitle: 'تقرير الأنشطة المحددة',
        activitySelectionReport: 'Activity selection report',
        searchPlaceholder: 'بحث في جميع الحقول...',
        printButton: 'طباعة المحدد',
        prevButton: 'السابق',
        nextButton: 'التالي',
        loading: 'جاري التحميل...',
        noSelectionError: 'يرجى تحديد نشاط واحد على الأقل للطباعة',
        autoGenerated: 'تم إنشاء هذا التقرير آلياً عبر مستعرض الأنشطة',
        activityId: 'رمز النشاط',
        descriptionAr: 'البيان (عربي)',
        descriptionEn: 'البيان (English)',
        classification: 'التصنيف',
        saudisPercentage: 'نسبة السعوديين',
        date: 'التاريخ',
        activityCount: 'عدد الأنشطة',
        jsonArrayTitle: 'معرفات الأنشطة المختارة (JSON Array)',
        langToggle: 'English',
        footerTimestamp: '-'
    }
};

function App() {
    const [activities, setActivities] = useState([]);
    const [loading, setLoading] = useState(true);
    const [searchTerm, setSearchTerm] = useState('');
    const [sortConfig, setSortConfig] = useState({ key: 'activityId', direction: 'asc' });
    const [currentPage, setCurrentPage] = useState(1);
    const [itemsPerPage] = useState(50);

    const { selectedActivityIds = [], language = 'en' } = useSelector((state) => state.selection || {});
    const selectedIdsArray = selectedActivityIds;
    const dispatch = useDispatch();

    const t = translations[language] || translations.en;
    const isRtl = language === 'ar';
    const fil = "/uploads/151_new_29_dec_custom.json";
    // For optimized checks, we can create a Set locally from the Redux array
    const selectedIdsSet = useMemo(() => new Set(selectedIdsArray), [selectedIdsArray]);

    useEffect(() => {
        fetch(fil)
            .then(res => res.json())
            .then(data => {
                const mappedData = data.map(item => ({
                    activityId: item.activityId,
                    description: item.description,
                    description_EN: item.description_EN,
                    classification: item.isicMasterRule?.classification || 'N/A',
                    saudis_percentage: item.saudis_percentage
                }));
                setActivities(mappedData);
                setLoading(false);
            })
            .catch(err => {
                console.error('Error loading data:', err);
                setLoading(false);
            });
    }, []);

    // Reset to page 1 when search term changes
    useEffect(() => {
        setCurrentPage(1);
    }, [searchTerm]);

    const handleSelect = (id) => {
        dispatch(toggleActivitySelection(id));
    };

    const handleSelectAll = (e) => {
        if (e.target.checked) {
            dispatch(setActivitySelection(filteredActivities.map(a => a.activityId)));
        } else {
            dispatch(clearActivitySelection());
        }
    };

    const requestSort = (key) => {
        let direction = 'asc';
        if (sortConfig.key === key && sortConfig.direction === 'asc') {
            direction = 'desc';
        }
        setSortConfig({ key, direction });
    };

    const filteredActivities = useMemo(() => {
        let result = activities.filter(activity =>
            activity.activityId.toLowerCase().includes(searchTerm.toLowerCase()) ||
            activity.description.toLowerCase().includes(searchTerm.toLowerCase()) ||
            (activity.description_EN && activity.description_EN.toLowerCase().includes(searchTerm.toLowerCase())) ||
            activity.classification.toLowerCase().includes(searchTerm.toLowerCase()) ||
            activity.saudis_percentage.toLowerCase().includes(searchTerm.toLowerCase())
        );

        if (sortConfig.key) {
            result.sort((a, b) => {
                const aValue = a[sortConfig.key] || '';
                const bValue = b[sortConfig.key] || '';
                if (aValue < bValue) return sortConfig.direction === 'asc' ? -1 : 1;
                if (aValue > bValue) return sortConfig.direction === 'asc' ? 1 : -1;
                return 0;
            });
        }

        return result;
    }, [activities, searchTerm, sortConfig]);

    const totalPages = Math.ceil(filteredActivities.length / itemsPerPage);
    const currentItems = useMemo(() => {
        const indexOfLastItem = currentPage * itemsPerPage;
        const indexOfFirstItem = indexOfLastItem - itemsPerPage;
        return filteredActivities.slice(indexOfFirstItem, indexOfLastItem);
    }, [filteredActivities, currentPage, itemsPerPage]);

    const handlePrint = () => {
        if (selectedIdsArray.length === 0) {
            toast.error(t.noSelectionError, {
                style: {
                    borderRadius: '10px',
                    background: '#333',
                    color: '#fff',
                    fontFamily: isRtl ? 'IBM Plex Sans Arabic' : 'inherit'
                },
            });
            return;
        }
        window.print();
    };

    const toggleLang = () => {
        dispatch(setLanguage(language === 'en' ? 'ar' : 'en'));
    };
    const selectedActivities = useMemo(() => {
        return activities.filter(a => selectedIdsSet.has(a.activityId));
    }, [activities, selectedIdsSet]);

    const getPageNumbers = () => {
        const pageNumbers = [];
        const maxVisiblePages = 7;

        if (totalPages <= maxVisiblePages) {
            for (let i = 1; i <= totalPages; i++) {
                pageNumbers.push(i);
            }
        } else {
            let startPage = Math.max(1, currentPage - 2);
            let endPage = Math.min(totalPages, startPage + 4);

            if (endPage === totalPages) {
                startPage = Math.max(1, endPage - 4);
            }

            if (startPage > 1) {
                pageNumbers.push(1);
                if (startPage > 2) pageNumbers.push('...');
            }

            for (let i = startPage; i <= endPage; i++) {
                pageNumbers.push(i);
            }

            if (endPage < totalPages) {
                if (endPage < totalPages - 1) pageNumbers.push('...');
                pageNumbers.push(totalPages);
            }
        }
        return pageNumbers;
    };

    if (loading) return <div className="container" dir={isRtl ? 'rtl' : 'ltr'}>{t.loading}</div>;

    return (
        <div className="container" dir={isRtl ? 'rtl' : 'ltr'}>
            <Toaster position="top-center" reverseOrder={false} />
            {/* Screen View */}
            <div className="no-print">
                <header style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '1rem', position: 'relative' }}>
                    <div style={{ position: 'absolute', [isRtl ? 'left' : 'right']: '0', top: '0' }}>
                        <button className="secondary" onClick={toggleLang}>
                            {t.langToggle}
                        </button>
                    </div>
                    <div style={{ display: 'flex', width: '100%', justifyContent: 'center', alignItems: 'center' }}>
                        <img style={{ maxWidth: '400px', height: 'auto' }} src="/assets/logo.png" alt="logo" />
                    </div>
                </header>

                <h1 style={{ textAlign: 'center', marginTop: '1rem', fontFamily: isRtl ? 'IBM Plex Sans Arabic' : 'inherit', marginBottom: '1rem', fontSize: 'clamp(1.5rem, 5vw, 2.5rem)' }}>
                    {t.title}
                </h1>

                <div className="card" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '1rem', flexWrap: 'wrap' }}>
                    <div className="search-bar" style={{ flex: '1 1 300px' }}>
                        <div style={{ position: 'relative' }}>
                            <Search size={20} style={{ position: 'absolute', [isRtl ? 'right' : 'left']: '12px', top: '50%', transform: 'translateY(-50%)', color: '#94a3b8' }} />
                            <input
                                type="text"
                                placeholder={t.searchPlaceholder}
                                value={searchTerm}
                                onChange={(e) => setSearchTerm(e.target.value)}
                                style={{ [isRtl ? 'paddingRight' : 'paddingLeft']: '40px', width: '100%' }}
                            />
                        </div>
                    </div>

                    <button onClick={handlePrint} style={{ whiteSpace: 'nowrap', width: '100%', maxWidth: 'none' }}>
                        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                            <Printer size={18} style={{ [isRtl ? 'marginLeft' : 'marginRight']: '8px' }} />
                            {t.printButton} ({selectedIdsArray.length})
                        </div>
                    </button>
                </div>

                <div className="card">
                    <div className="table-wrapper">
                        <table>
                            <thead>
                                <tr>
                                    <th className="checkbox-cell">
                                        <input
                                            type="checkbox"
                                            onChange={handleSelectAll}
                                            checked={selectedIdsArray.length === filteredActivities.length && filteredActivities.length > 0}
                                        />
                                    </th>
                                    <th onClick={() => requestSort('activityId')}>
                                        {t.activityId}
                                        {sortConfig.key === 'activityId' ? (sortConfig.direction === 'asc' ? <ChevronUp size={14} /> : <ChevronDown size={14} />) : <ArrowUpDown size={14} />}
                                    </th>
                                    <th onClick={() => requestSort('description')}>{t.descriptionAr}</th>
                                    <th onClick={() => requestSort('description_EN')}>{t.descriptionEn}</th>
                                    <th onClick={() => requestSort('classification')}>{t.classification}</th>
                                    <th onClick={() => requestSort('saudis_percentage')}>{t.saudisPercentage}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {currentItems.map(activity => (
                                    <tr key={activity.activityId}>
                                        <td className="checkbox-cell">
                                            <input
                                                type="checkbox"
                                                checked={selectedIdsSet.has(activity.activityId)}
                                                onChange={() => handleSelect(activity.activityId)}
                                            />
                                        </td>
                                        <td data-label={t.activityId}>{activity.activityId}</td>
                                        <td data-label={t.descriptionAr}>{activity.description}</td>
                                        <td data-label={t.descriptionEn} style={{ direction: 'ltr', textAlign: isRtl ? 'right' : 'left' }}>{activity.description_EN || '-'}</td>
                                        <td data-label={t.classification}>
                                            <span className={`badge ${activity.classification === 'Allowed' ? 'badge-allowed' : 'badge-restricted'}`}>
                                                {activity.classification}
                                            </span>
                                        </td>
                                        <td data-label={t.saudisPercentage}>{activity.saudis_percentage}</td>
                                    </tr>
                                ))}
                                {
                                    currentItems.length === 0 && (
                                        <tr>
                                            <td colSpan="6" style={{ textAlign: 'center', padding: '2rem' }}>No activities found</td>
                                        </tr>
                                    )
                                }
                            </tbody>
                        </table>
                    </div>

                    <div className="pagination" style={{ marginTop: '1.5rem', borderTop: '1px solid var(--border)', paddingTop: '1.5rem', flexWrap: 'wrap', justifyContent: 'center', gap: '1rem' }}>
                        <button
                            className="secondary icon-btn"
                            onClick={() => {
                                setCurrentPage(prev => Math.max(prev - 1, 1));
                                window.scrollTo({ top: 0, behavior: 'smooth' });
                            }}
                            disabled={currentPage === 1}
                            style={{ order: isRtl ? 3 : 1 }}
                        >
                            {t.prevButton}
                        </button>
                        <div className="page-numbers" style={{ order: 2 }}>
                            {getPageNumbers().map((number, index) => (
                                <button
                                    key={index}
                                    className={`page-btn ${currentPage === number ? 'active' : ''} ${number === '...' ? 'dots' : ''}`}
                                    onClick={() => {
                                        if (typeof number === 'number') {
                                            setCurrentPage(number);
                                            window.scrollTo({ top: 0, behavior: 'smooth' });
                                        }
                                    }}
                                    disabled={number === '...'}
                                >
                                    {number}
                                </button>
                            ))}
                        </div>
                        <button
                            className="secondary icon-btn"
                            onClick={() => {
                                setCurrentPage(prev => Math.min(prev + 1, totalPages));
                                window.scrollTo({ top: 0, behavior: 'smooth' });
                            }}
                            disabled={currentPage === totalPages || totalPages === 0}
                            style={{ order: isRtl ? 1 : 3 }}
                        >
                            {t.nextButton}
                        </button>
                    </div>
                </div>
            </div>

            {/* Print View (Only visible when printing) */}
            <div className="print-only" dir={isRtl ? 'rtl' : 'ltr'}>
                <div className="print-report-header">
                    <div className="report-title-section">
                        <div style={{ display: 'inline-block', width: '100%', alignItems: 'center', gap: '1rem' }}>
                            <img style={{ maxWidth: '300px', height: 'auto' }} src="/assets/logo.png" alt="logo" />
                        </div>
                        <h1>{t.reportTitle}</h1>
                        <p className="report-subtitle">{t.activitySelectionReport}</p>
                    </div>
                    <div className="report-meta-section">
                        <div className="meta-item">
                            <span className="meta-label">{t.date}:</span>
                            <span className="meta-value">{new Date().toLocaleDateString(isRtl ? 'ar-SA' : 'en-US')}</span>
                        </div>
                        <div className="meta-item">
                            <span className="meta-label">{t.activityCount}:</span>
                            <span className="meta-value">{selectedActivities.length}</span>
                        </div>
                    </div>
                </div>

                <table className="print-table">
                    <thead>
                        <tr>
                            <th style={{ width: '15%' }}>{t.activityId}</th>
                            <th style={{ width: '35%' }}>{t.descriptionAr}</th>
                            <th style={{ width: '30%' }}>{t.descriptionEn}</th>
                            <th style={{ width: '10%' }}>{t.classification}</th>
                            <th style={{ width: '10%' }}>{t.saudisPercentage}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {selectedActivities.map(activity => (
                            <tr key={activity.activityId}>
                                <td className="font-mono">{activity.activityId}</td>
                                <td className="ar-text">{activity.description}</td>
                                <td className="en-text">{activity.description_EN || '-'}</td>
                                <td>{activity.classification}</td>
                                <td>{activity.saudis_percentage}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>

                {/* Selected IDs Export Section (Bottom of Print) */}
                <div className="print-data-footer">
                    <h3>{t.jsonArrayTitle}</h3>
                    <div className="id-array-box">
                        {JSON.stringify(selectedIdsArray)}
                    </div>
                </div>

                <div className="print-footer">
                    <p>{t.autoGenerated} - {new Date().toLocaleTimeString(isRtl ? 'ar-SA' : 'en-US')}</p>
                </div>
            </div>

            <style>{`
        .print-only { display: none; }
        
        @media print {
          .no-print { display: none !important; }
          .print-only { 
            display: block !important; 
            background: white;
            color: black;
          }
          
          @page {
            margin: 15mm;
            size: A4;
          }
          
          body { 
            background: white; 
            padding: 0;
            font-size: 11pt;
            font-family: inherit;
          }
          
          [dir="rtl"] body {
            font-family: 'IBM Plex Sans Arabic', sans-serif;
          }
          
          .container { 
            max-width: none; 
            width: 100%; 
            padding: 0;
            margin: 0;
          }
          
          .print-report-header {
            display: flex;
            justify-content: space-between;
            align-items: flex-end;
            margin-bottom: 2rem;
            border-bottom: 3px solid #1a1a1a;
            padding-bottom: 1rem;
          }
          
          .report-title-section h1 {
            font-size: 24pt;
            margin-bottom: 0.25rem;
            color: #1a1a1a;
          }
          
          .report-subtitle {
            font-size: 10pt;
            color: #666;
            text-transform: uppercase;
            letter-spacing: 1px;
          }
          
          .report-meta-section {
            text-align: ${isRtl ? 'left' : 'right'};
            font-size: 10pt;
          }
          
          .meta-item {
            margin-bottom: 0.25rem;
          }
          
          .meta-label {
            font-weight: bold;
            margin-${isRtl ? 'left' : 'right'}: 0.5rem;
          }
          
          .print-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 2rem;
          }
          
          .print-table th {
            background-color: #f3f4f6 !important;
            border: 1px solid #d1d5db;
            color: black;
            font-weight: bold;
            padding: 10px;
            text-align: ${isRtl ? 'right' : 'left'};
          }
          
          .print-table td {
            border: 1px solid #d1d5db;
            padding: 8px 10px;
            vertical-align: top;
            line-height: 1.4;
            text-align: ${isRtl ? 'right' : 'left'};
          }
          
          .print-table tr:nth-child(even) {
            background-color: #f9fafb !important;
          }
          
          .font-mono { font-family: monospace; font-weight: bold; }
          .en-text { direction: ltr; text-align: left; }
          .ar-text { direction: rtl; text-align: right; }

          .print-data-footer {
            margin-top: 2rem;
            page-break-inside: avoid;
          }

          .print-data-footer h3 {
            font-size: 12pt;
            margin-bottom: 0.5rem;
            border-bottom: 1px solid #e5e7eb;
            padding-bottom: 0.25rem;
          }

          .id-array-box {
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            padding: 1rem;
            font-family: monospace;
            font-size: 9pt;
            word-break: break-all;
            line-height: 1.5;
            border-radius: 4px;
          }
          
          .print-footer {
            margin-top: 3rem;
            border-top: 1px solid #e5e7eb;
            padding-top: 1rem;
            text-align: center;
            font-size: 9pt;
            color: #6b7280;
          }
        }
      `}</style>
        <Analytics />
        </div>
    );
}

export default App;
